---
title: About Me
output: 
  blogdown::html_page:
    toc: true
slug: about-me
---

## Summary

I am a versatile and experienced data scientist who, above all else, excels at data mining and predictive analytics for the purpose of helping functional business areas leverage new ways of conducting business. 

- In 2017, I created and executed a new way to predict Medicare Star measure thresholds using a blend of linear regression, ARIMA forecasting, and hierarchical clustering. This model supported data-driven planning and contributed to $30M in revenue thanks to a 40% improvement in accuracy over the previous methodology. 

- In 2019, I created and launched a new data science product within my organization called SimText that automatically audits marketing mailing lists on a large scale using a novel blend of statistical text similarity and classification, enabling 100% coverage of data audits at 99% accuracy.

- In 2020, I created a new member retention strategy that uses predictive analytics to identify customers who are most likely to churn based on factors related to product, price, experience, location, and socio-psychological characteristics. Using the top quantile of customers with the highest churn probability, the model offers a 700% increase in precision over random selection.

Though my primary focus is on solving business problems, I am passionate about discovering and utilizing modern technology to solve new problems and raise the standards of data science. In addition to my standard toolkit (R, SQL, Python, Git), I have successfully integrated AWS (SageMaker, Lambda, API Gateway), Docker, and Shiny into my everyday work routines.

## Areas of Interest

The subjects that interest me the most include (in no particular order):

- Analytics
  - Time series forecasting and trend analytics
  - Regression and classification
  - Cluster analysis and segmentation
  - Outlier analysis
  - Dimension reduction
  - Descriptive statistics
  - Data visualization
  - Writing and presenting
  - Productionizing models
- Applications
  - Customer analytics
  - Customer segmentation
  - Marketing analytics
  - Sales analytics
  - Demand forecasting
  - Geographic segmentation

## Technology Stack

- R
- SQL
- Python
- AWS
- Git
- Docker
- R Shiny

## Data Science without a STEM Degree

I am often asked how I got into data science without a STEM degree. My answer is usually split into two parts:

1. Studying sociology inspired me to learn more about myself and society using data, analytics, experimentation, and critical thinking as the mechanisms.

2. One of my first undergraduate courses got me hooked on statistics, data visualization, and R programming. From that point on, I was fiercely motivated to learn more about these topics, spending at least 5-10 hours a week reading and developing new skills outside of my normal classwork. Through hard work and constant learning, I acquired the skills to become a data scientist.
