---
title: Row-wise Max Values for a Sparse Matrix Using RcppArmadillo
author: Danny Morris
date: '2019-07-01'
output: 
  blogdown::html_page:
    toc: true
slug: row-wise-min-and-max-values-in-a-sparse-matrix
categories:
  - R
tags:
  - Rcpp
  - R
editor_options: 
  chunk_output_type: console
---

This document demonstrates how to extract maximum values for each row in a sparse matrix using RcppArmadillo for speed and efficiency.


```{r, warning = F}
library(Matrix)
library(Rcpp)
library(RcppArmadillo)
library(magrittr)
```

A sample sparse matrix implemented in the Matrix pacakge. 

```{r}
i <- c(1,3:8) 
j <- c(2,9,6:10)
x <- 7 * (1:7)

sparse_matrix <- sparseMatrix(i, j, x = x) 

sparse_matrix
```

# Using Inline Functions

```{r, eval = F}
rowwise_max <- Rcpp::cppFunction(
  "arma::sp_mat sp_row_max(arma::sp_mat X) {
   return arma::max(X, 1);
  }", depends= "RcppArmadillo"
)

rowwise_max_idx <- Rcpp::cppFunction(
  "arma::urowvec sp_row_max_id(arma::sp_mat X) {
   return arma::index_max(X.t(), 0);
  }", depends= "RcppArmadillo"
)
```

```{r, eval = F}
rowwise_max(sparse_matrix) %>% as.vector()

rowwise_max_idx(sparse_matrix) %>% as.vector()
```

# Sourcing a .cpp File

`rowwise_max.cpp`

```{Rcpp, eval = F}
# include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
arma::urowvec rowwise_max2(arma::sp_mat X) {
  return arma::index_max(X, 1);
}

// [[Rcpp::export]]
arma::sp_mat rowwise_max_idx2(arma::sp_mat X) {
  return arma::max(X.t(), 0);
}
```

```{r, eval = F}
rowwise_max2(sparse_matrix) %>% as.vector()
rowwise_max_idx2(sparse_matrix) %>% as.vector()
```





