---
title: Image Tessearch Using Python and OpenCV
author: Danny Morris
date: '2019-04-09'
output: 
  blogdown::html_page:
    toc: true 
slug: image-tessearch-using-python-and-opencv
categories:
  - Python
  - Computer Vision
tags:
  - Computer Vision
  - Python
editor_options: 
  chunk_output_type: console
---

```{r}
#library(reticulate)

#reticulate::use_condaenv("computer-vision")
```

```{r}
# import the necessary packages
#from skimage.measure import compare_ssim
#import argparse
#import imutils
#import cv2

#import matplotlib.pyplot as plt
#import matplotlib.image as mpimg
#import numpy as np
```

```{r}
# load the two input images
#imageA = cv2.imread("static/img/credit-cards/card.PNG")
#imageB = cv2.imread("static/img/credit-cards/card2.PNG")
```

```{r}
#imageA_resize = cv2.resize(imageA, (300, 200))    
#imageB_resize = cv2.resize(imageB, (300, 200))
```

```{r}
# convert the images to grayscale
#grayA = cv2.cvtColor(imageA_resize, cv2.COLOR_BGR2GRAY)
#grayB = cv2.cvtColor(imageB_resize, cv2.COLOR_BGR2GRAY)
```

```{r}
#plt.imshow(grayA, cmap = 'gray')
#plt.show()
```

```{r}
#def plot_img(image):
#  plt.imshow(image)
#  plt.show()
```

```{python}
#plot_img(grayB)
```

